// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6rSYM3NIHi_uTitKkTqJUKJRKLlf21SE',
    appId: '1:870300714437:web:b033c9a7e38e56c1c077ac',
    messagingSenderId: '870300714437',
    projectId: 'my-bootcamp-notes',
    authDomain: 'my-bootcamp-notes.firebaseapp.com',
    storageBucket: 'my-bootcamp-notes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAivq1sOqGueWkZyFUmlLngNPAt8e3GEDE',
    appId: '1:870300714437:android:01d48daabd33384fc077ac',
    messagingSenderId: '870300714437',
    projectId: 'my-bootcamp-notes',
    storageBucket: 'my-bootcamp-notes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWoQADE0hf9wXZ64FCg8V7GTBA7JABtJY',
    appId: '1:870300714437:ios:f5b8fc00ab13ead2c077ac',
    messagingSenderId: '870300714437',
    projectId: 'my-bootcamp-notes',
    storageBucket: 'my-bootcamp-notes.firebasestorage.app',
    iosBundleId: 'com.example.myBootcampNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWoQADE0hf9wXZ64FCg8V7GTBA7JABtJY',
    appId: '1:870300714437:ios:f5b8fc00ab13ead2c077ac',
    messagingSenderId: '870300714437',
    projectId: 'my-bootcamp-notes',
    storageBucket: 'my-bootcamp-notes.firebasestorage.app',
    iosBundleId: 'com.example.myBootcampNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6rSYM3NIHi_uTitKkTqJUKJRKLlf21SE',
    appId: '1:870300714437:web:4069add60413c507c077ac',
    messagingSenderId: '870300714437',
    projectId: 'my-bootcamp-notes',
    authDomain: 'my-bootcamp-notes.firebaseapp.com',
    storageBucket: 'my-bootcamp-notes.firebasestorage.app',
  );
}
